[package]
name = "strim"
version = "0.1.0"
edition = "2024"

[dependencies]
cpal = "0.16.0"
ringbuf = "0.4.8"
eframe = "0.32.3"
egui_plot = "0.33.0"
anyhow = "1.0.99"
clap = { version = "4.5.47", features = ["derive"] }
