[package]
name = "strim-shared"
version = "0.1.0"
edition = "2021"

[dependencies]
cpal = { workspace = true }
anyhow = { workspace = true }
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
